### ISSUE TITLE
PUT and DELETE working?

### ISSUE THREAD

**Issue by jonaszuberbuehler** [sneas/ionic-native-http-connection-backend#1]
Skimming your code I saw that PUT and DELETE methods are supposed to work with the native backend. Is that true? Looking at https://github.com/wymsee/cordova-HTTP/blob/master/src/ios/CordovaHttpPlugin.h and https://github.com/wymsee/cordova-HTTP/issues/111 I get the impression they don't.

Would be nice if they work!

**Comment by sneas** [comment]
Judging by amount of opened pull requests and the last commit date https://github.com/wymsee/cordova-HTTP is not maintained anymore so I forked it into https://github.com/sneas/cordova-HTTP and added PUT, DELETE and postJson methods.

In readme you can find the installation step:
```
ionic cordova plugin add https://github.com/sneas/cordova-HTTP
```

**Comment by jonaszuberbuehler** [comment]
Ah my bad, didn't get that. Thx for the clarification!
