### ISSUE TITLE
Post FormData Error

### ISSUE THREAD

**Issue by arfaWong** [sneas/ionic-native-http-connection-backend#10]

**Comment by arfaWong** [comment]
https://github.com/sneas/ionic-native-http-connection-backend/blob/6881352deab09b843c32843041b090fade59dc84/src/native-http-backend.ts#L130

**Comment by sneas** [comment]
Can you explain this please?

**Comment by arfaWong** [comment]
@sneas  when upload a image using Http post and FormData.

**Comment by sneas** [comment]
I'll have a deeper look at it, but I would recommend you to use this plugin for uploading and downloading files https://ionicframework.com/docs/native/file-transfer/

**Comment by sneas** [comment]
Closing in favour of https://ionicframework.com/docs/native/file-transfer/
