### ISSUE TITLE
Question about the library's intended use

### ISSUE THREAD

**Issue by dgoldm** [sneas/ionic-native-http-connection-backend#100]
Thanks for this excellent library.
In my case, the app is sending CORS requests to a server that has CORS configured correctly, but I'm experiencing 2 other CORS related problems:
1) My app won't run on iOS devices that have the Safari setting "prevent cross-site tracking" turned on (which it is by default).
2) It won't run on the iOS simulator at all (even if the above setting is turned off).
Your library has solved both these problems.

I'm just curious about the fact that you don't mention these use cases in the docs. Even stranger, I can't find on the web even a single developer complaining about similar problems. I would expect them to be rather widespread. Could there be something I'm doing wrong in my Ionic app, that forces me to use your library?

**Comment by sneas** [comment]
Hi, I don't think you're doing anything wrong the library solves the CORS issue for you. The library acts as an adapter between `HttpClient` and `cordova-plugin-advanced-http`. The requests get performed by `cordova-plugin-advanced-http` whenever possible (ie the app is running on device and the plugin was properly installed). The cordova plugin is an independent application that works outside of the Safari browser. In other words: Safari's preferences and restrictions do not affect the plugin's behavior.
