### ISSUE TITLE
POST requests with json primitives not being sent correctly

### ISSUE THREAD

**Issue by dgoldm** [sneas/ionic-native-http-connection-backend#101]
When trying to send a POST request with content-type: application/json, where the body is a primitive json value (e.g. string or number), the request is actually sent with an empty body.
For instance:
1. `this.httpClient.post(myUrl, 123)`
When I peek at this request when it arrives at the server, I see:
content-type: application/json
content-length: 2
and the body of the request is an empty json object:   {}
      
2. `this.httpClient.post(myUrl, "abc", { headers: new HttpHeaders({'content-type': 'application/json'}) })`
This request is sent with a completely empty body (content-length: 0) (in this case, if I don't set the content-type header explicity, it is sent as application/x-www-form-urlencoded )

These calls work as expected when falling back to the Angular HttpClient (e.g. when I run the app via ionic serve, or when running on Android) - the content-type is always application/json by default, and the request body contains the literal that I specified.

**Comment by sneas** [comment]
Hi, thank you for the issue and the detailed reproduction steps. I'll check what I can do ASAP.

**Comment by dgoldm** [comment]
Hi @sneas,
Do you have any plans to fix this? In the meantime I've implemented a workaround by wrapping all primitives in an object, and unwrapping them at the backend, but it would be nice to do without it.

**Comment by sneas** [comment]
Hi @dgoldm. Thank you for kicking me with that issue. The last time I was trying to debug it, the blocker seemed to be on `@ionic-native/http` side. I'm trying to debug it again, but my test app isn't compiling after the MacOS update. Trying to fix that right now. Will update you as soon as I get some progress with the issue.

**Comment by sneas** [comment]
So apparently, we're limited by `cordova-plugin-advanced-http`.

I've created an issue with a question https://github.com/silkimen/cordova-plugin-advanced-http/issues/324

Let's see where it will lead us.
