### ISSUE TITLE
Following instruction guidelines with Ionic 4 will result in   NullInjectorError: No provider for NativeHttpBackend! error

### ISSUE THREAD

**Issue by LouAdrien** [sneas/ionic-native-http-connection-backend#110]
Hello, when following the installation guidelines, and modifying app.module.ts as explained, I get the following issue while accessing the app :
`
NullInjectorError: StaticInjectorError(AppModule)[HttpBackend -> NativeHttpBackend]: 
  StaticInjectorError(Platform: core)[HttpBackend -> NativeHttpBackend]: 
    NullInjectorError: No provider for NativeHttpBackend!
`

Is it a known issue? Is the plugin even compatible with Ionic 4?

Regards,

**Comment by sneas** [comment]
Hi, you may consider using version `6.2.x`. It's compatible with Angular 8 and Ionic 4.
