### ISSUE TITLE
Unsupported application/x-www-form-urlencoded request

### ISSUE THREAD

**Issue by log2c** [sneas/ionic-native-http-connection-backend#111]
I'm sorry my bad english    **;(**

When i send application/x-www-form-urlencoded  request in ionic4 (on real device ), there is something wrong with library detect content-type. 

I want to post key-value request

![image](https://user-images.githubusercontent.com/9973322/75124395-de969280-56e9-11ea-85b3-8218001cd4d8.png)

but the library post 

![image](https://user-images.githubusercontent.com/9973322/75124383-c7f03b80-56e9-11ea-9811-98bc8946a0e9.png)

**Finally, i find a solution to avoid problem**

```js
(this.httpBackend as any).getSerializerTypeByContentType = (req) => {
            const reqContentType = (req.headers.get('content-type') || '').toLocaleLowerCase();
            if (reqContentType.indexOf('text/') === 0) {
                return 'utf8';
            }
            if (reqContentType.indexOf('application/json') === 0) {
                return 'json';     // <==== I'm change this
            }   
            return 'urlencoded';
        };
```

Would you mind add this code in your library or give me other solution?

Do you understand what i say.....

**Comment by sneas** [comment]
Hi, this is probably related to #103. I have not started working on it yet.

What version of the library are you using?

**Comment by log2c** [comment]
> Hi, this is probably related to #103. I have not started working on it yet.
> 
> What version of the library are you using?

Hi master (or guru?),thanks for your reply.

```
"ionic-native-http-connection-backend": "5.0.4",
"cordova-plugin-advanced-http": "2.4.1",
"cordova-plugin-advanced-http": {
        "OKHTTP_VERSION": "3.10.0"
},
.........

"@angular/common": "^7.2.15",
"@angular/core": "^7.2.15",
"@angular/forms": "^7.2.15",
"@angular/http": "^7.2.15",
```

**Comment by sneas** [comment]
Hi, @log2c,

Sorry for big delays, I'm a bit busy nowadays. I'm about to pick up #103. But I have to warn you that the fix will not be applied to version 5.x of `ionic-native-http-connection-backend` because it's out of date.  The fix will be applied to 6.x and further versions. The main difference between version 5.x and 6.x is in Angular. 5.x uses Angular 7 and 6.x uses Angular 8.
