### ISSUE TITLE
Error in entry point

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [sneas/ionic-native-http-connection-backend#114]
Hi,

I have added the plugin to the ionic app and during ng build I am getting this error

`ERROR in Failed to compile entry-point ionic-native-http-connection-backend (main as commonjs) due to compilation errors:
node_modules/ionic-native-http-connection-backend/dist/native-http-module.js:16:22 - error NG1010: Value at position 0 in the NgModule.imports of NativeHttpModule is not a reference: [object Object]`

Thanks

**Comment by sneas** [comment]
Hi,

Could you please provide the output of `ionic info` command and versions of

* `@ionic-native/core`
* `ionic-native-http-connection-backend`

Thank you.

**Comment by saoron** [comment]
Same issue here:


```
Ionic:

   Ionic CLI                     : 6.1.0 (/Users/saoron/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.2
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 9.0.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.10.0) : 0.6.0
   native-run (update available: 0.3.0)   : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/saoron/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.14.1 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504


```

**Comment by saoron** [comment]
I can confirm this works on 7.x version, I think it's safe to push it to the latest channel on npm..

**Comment by sneas** [comment]
@saoron , you're right. Added 7.0.3 to the latest.
