### ISSUE TITLE
Incompatible with Angular 9.1

### ISSUE THREAD

**Issue by askarby** [sneas/ionic-native-http-connection-backend#115]
I updated my application to Angular 9.1, and now I'm not able to start my application.

**Steps to reproduce:**

Update an existing Angular application (I updated one running on Angular 9), by issuing the following command:

```
ng update @angular/cli @angular/core
```

Then start the application, by typing:

```
ng serve
```

**Error:**

When "serving" the application, you'll then see the following error:

```
ERROR in node_modules/ionic-native-http-connection-backend/dist/native-http-backend.d.ts:9:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

9     static ɵfac: i0.ɵɵFactoryDef<NativeHttpBackend>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.d.ts:12:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

12     static ɵfac: i0.ɵɵFactoryDef<NativeHttpFallback>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sneas** [comment]
What version of the library are you using?

**Comment by askarby** [comment]
Sorry, forgot to mention that.... we're using v. 7.0.3 (latest)

**Comment by devagrawal09** [comment]
Facing the same issue

**Comment by rbenzing** [comment]
how do i fix this for Angular 8? i get this exact error but not on 9. I tried using the v8.0.0 code but giving the same error

**Comment by sneas** [comment]
@rbenzing everything after v7.0.0 is for Angular 9.x with no backward compatibility. v6.2.3 should work for you.
