### ISSUE TITLE
Ionic 5 Android Issue

### ISSUE THREAD

**Issue by richardkshergold** [sneas/ionic-native-http-connection-backend#124]
I have been using version 4.0.7 of this plugin in our Ionic 3 app for 18 months and it has been working fine in browser, iOS and Android.  The app uses the angular HttpClient for all its calls.

In my app module I have the following:

```
// see https://github.com/sneas/ionic-native-http-connection-backend/issues/15
    {
      provide: HttpBackend,
      useFactory: (platform: Platform, nativeHttpBackend: NativeHttpBackend, httpXhrBackend: HttpXhrBackend) => {
        if (platform.is('android')) {
          return httpXhrBackend;
        } else {
          return new NativeHttpFallback(platform, nativeHttpBackend, httpXhrBackend);
        }
      },
      deps: [Platform, NativeHttpBackend, HttpXhrBackend]
    },
```

I have migrated the app to Ionic 5 and my calls all work ok in the browser and in iOS but in Android they result in a CORS error.

I've tried the latest version of the plugin and also reverting back to 4.0.7. I've also tried leaving the code as above and replacing it with the code you suggest i.e: 

```
{
      provide: HttpBackend,
      useClass: NativeHttpFallback,
      deps: [Platform, NativeHttpBackend, HttpXhrBackend],
},
```

If I have the code as above i.e without the Android check then when the calls are made in Android absolutely nothing happens - no CORS error, no response from server, no errors at all - nothing.  If I replace it with my first section of code then I get CORS errors (which do not occur in our Ionic 3 app)

Do you have any suggestions?   Here is my Ionic info output:

```
Ionic:

   Ionic CLI                     : 6.11.0 (/Users/xxx/.nvm/versions/node/v12.16.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.5
   @angular-devkit/schematics    : 10.0.3
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (5 plugins total)

Utility:

   cordova-res (update available: 0.15.1) : 0.12.2
   native-run                             : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : ios-sim/9.0.0 darwin-x64 node-v12.16.2
   NodeJS     : v12.16.2 (/Users/xxx/.nvm/versions/node/v12.16.2/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.6 Build version 11E708
```

**Comment by sneas** [comment]
It seems like (and I might be wrong) `HTTP` service hasn't been installed properly on Android.

Have you considered checking out this troubleshooting technique on Android https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md ? This is how we can make sure `HTTP` service is working correctly on the device.

**Comment by richardkshergold** [comment]
Thanks for the quick response @sneas - unfortunately it is installed as I get the "installed correctly" message on the console.  Do you have any other suggestions?

**Comment by renanrider** [comment]
@richardkshergold Apparently the problem occurs with the other plugin, not this one.

Look this:
https://github.com/sneas/ionic-native-http-connection-backend/issues/126

**Comment by sneas** [comment]
Hi @richardkshergold, sorry for the late reply. I finally found some time to install Android emulator on my machine to reproduce the supposed issue on the latest version of the library. Unfortunately, I can't see any problem. Here is the working example https://github.com/sneas/ionic-5-http-test

Feel free to reopen the issue if the problem still exists.
