### ISSUE TITLE
Android PUT request with a number as body results in error code 599

### ISSUE THREAD

**Issue by digaus** [sneas/ionic-native-http-connection-backend#127]
### Subject of the issue
Describe your issue here.

### Environment
* version of angular: 7.2.15
* version of ionic-native-http-connection-backend: 6.2.3
* version of @ionic/angular: 4.11.7
* version of @ionic-native/http: 5.18.0

### Steps to reproduce

Create a put request with content type set to application/json. Just send a number and not an object as body ->

`put('test', 121231)`

### Expected behaviour
Request is working in web but not on Android with this plugin.

### Actual behaviour

Fails with errorCode 599 -> Similar to https://github.com/sneas/ionic-native-http-connection-backend/issues/15

But that "solution" does not work because Android now also has CORS issues.

**Comment by sneas** [comment]
Have you tried v6.2.4? It fixes a lot of bugs.

Also, Android version of `cordova-plugin-advanced-http`  have some problems mentioned [here](https://github.com/sneas/ionic-native-http-connection-backend/issues/126#issuecomment-685254039), have you considered disabling the plugin for Android at all as [this comment](https://github.com/sneas/ionic-native-http-connection-backend/issues/15#issuecomment-383997564) suggests?

**Comment by benallard** [comment]
Duplicate of #101 . Thanks for the hint!

**Comment by digaus** [comment]
> Have you tried v6.2.4? It fixes a lot of bugs.
> 
> Also, Android version of `cordova-plugin-advanced-http` has some problems mentioned [here](https://github.com/sneas/ionic-native-http-connection-backend/issues/126#issuecomment-685254039), have you considered disabling the plugin for Android at all as [this comment](https://github.com/sneas/ionic-native-http-connection-backend/issues/15#issuecomment-383997564) suggests?

Yep thanks for the info. Somehow I missed the latest release. Still have an issue when sending empty POST requests without a body. But will check and open a new issue for that.
