### ISSUE TITLE
Error 599 when sending empty body with POST (most likely PUT aswell)

### ISSUE THREAD

**Issue by digaus** [sneas/ionic-native-http-connection-backend#128]
### Environment
* version of angular: 7.2.15
* version of ionic-native-http-connection-backend: 6.2.4
* version of @ionic/angular: 4.11.7
* version of @ionic-native/http: 5.18.0

### Steps to reproduce

Create a post request with the body set to `null` or `undefined`->

`post('test', null)`

### Expected behaviour
Request is working in web but not on Android with this plugin.

### Actual behaviour

Getting this error:

`message: "Http failure response for (unknown url): 599 undefined"`

-> Similar to https://github.com/sneas/ionic-native-http-connection-backend/issues/15

Our Logout request is a POST without any content. Now I just send a dummy object everytime the body is not set as a workaround.

**Comment by IanSkylegs** [comment]
I have the same issue
