### ISSUE TITLE
How to support  angularjsV4.3 above common/http?

### ISSUE THREAD

**Issue by fssgh** [sneas/ionic-native-http-connection-backend#13]
How to support  angularjsV4.3 above common/http?

**Comment by sneas** [comment]
Good point. For now library supports `HttpModule` before v4.3. As soon as the project I'm working on is upgraded to the latest Angular version, I'm going to introduce `HttpClientModule` support. For now I can only suggest you to use `HttpModule` on your project which is deprecated but still available.

**Comment by sneas** [comment]
#21
