### ISSUE TITLE
When LazyLoading module in angular with IVY enabled, calls are going via default HttpXhrBackend and not NativeHttpBackend

### ISSUE THREAD

**Issue by Praveenram87** [sneas/ionic-native-http-connection-backend#130]
### Subject of the issue
When LazyLoading module in angular, its picking up the default HttpXhrBackend and not NativeHttpBackend

### Environment
* version of angular
* version of ionic-native-http-connection-backend
* version of @ionic/angular
* version of @ionic-native/http

### Steps to reproduce
LazyLoad Module with IVY enabled and see if calls are going via NativeHttpBackend

### Expected behaviour
HTTP calls should go via NativeHttpBackend and not HttpXhrBackend

### Actual behaviour
HTTP calls is going via  HttpXhrBackend and not NativeHttpBackend

**Comment by sneas** [comment]
Hi @Praveenram87, sorry for so late response. Could you provide the following data so I can reproduce the issue?

- version of angular
- version of ionic-native-http-connection-backend
- version of @ionic/angular
- version of @ionic-native/http

I'm closing the ticket for now. Feel free to reopen it if the issue still persists.
