### ISSUE TITLE
8.1.2 release as latest (currently next)

### ISSUE THREAD

**Issue by askarby** [sneas/ionic-native-http-connection-backend#135]
### Subject of the issue
The 8.1.2 release is currently marked as `next`, which prevents us from using it in production (as `8.1.2` is identified as a release candidate)

### Environment
n/a

### Steps to reproduce
n/a

### Expected behaviour
`8.1.2` is released as `latest`

### Actual behaviour
`8.1.2` is released as `next`

![image](https://user-images.githubusercontent.com/44014/108356734-cbc77880-71ec-11eb-90aa-1a66e4f67fed.png)

**Comment by sneas** [comment]
Hi @askarby, as you requested, `8.1.2` has just been tagged as `latest`.

**Comment by askarby** [comment]
Lovely @sneas - thank you 👍
