### ISSUE TITLE
415 undefined","error":{"error":"RESTEASY003065: Cannot consume content type"}} from device

### ISSUE THREAD

**Issue by takhil** [sneas/ionic-native-http-connection-backend#137]
### Browser redirection failing because of unsupported content-type
using single sign on from device while authentication the http throws error(Cannot consume content type) I'm sure this is from native-http because the calls are getting intercepted with native package

### Environment
* version of angular - 10.2.4
* version of ionic-native-http-connection-backend - 8.1.3
* version of @ionic/angular - 5.5.2
* version of @ionic-native/http - 3.1.0

### Steps to reproduce
No steps to reproduce because this is our private site

### Expected behaviour
In version 8.0.0 we are able to navigate and I'm using this package for a while. but for some of endpoints  API's returns undefined 599 error so we found this and updated package to 8.1.3 and we are able to access all end points but now the actual browser redirection was blocked. some thing got updated and I'm missing. please guide us to resolve this

My initial thought was around content type for native and angular 
FYI. - below is my content -type
			'Content-Type': 'application/json',
			'Accept': 'application/json',

No issues with that package but the other

### Actual behaviour
The Http request should go through

**Comment by sneas** [comment]
Hi @takhil, I still don't understand the problem. Could you please reproduce the problem with this service?

https://httpbin.org/

Or with https://nghttp2.org/httpbin. I think the latter works better when it comes to testing redirects.

There is a better chance I can help if you show me any behaviour which is working with the standard Angular's HttpClient, but isn't working when the library is enabled. The 2 above services could be used as a backend for testing.
