### ISSUE TITLE
Uncaught Error: Type NativeHttpModule does not have 'ngModuleDef' property.

### ISSUE THREAD

**Issue by bahyusanciko** [sneas/ionic-native-http-connection-backend#147]
### Subject of the issue
Describe your issue here.

### Environment
* version of angular
* version of ionic-native-http-connection-backend
* version of @ionic/angular
* version of @ionic-native/http

### Steps to reproduce
Describe how to reproduce this issue.

### Expected behaviour
Describe what should happen.

### Actual behaviour
Describe what happens instead.
![image](https://user-images.githubusercontent.com/41245088/124562430-35c57f00-de69-11eb-9a32-3d0b2b805424.png)

**Comment by sneas** [comment]
Hi, could you please provide:

* version of angular
* version of ionic-native-http-connection-backend
* version of @ionic/angular
* version of @ionic-native/http

**Comment by bahyusanciko** [comment]
hai sir , version ionic me 
    "@angular/platform-browser": "^8.2.14",
    "@angular/pwa": "^0.803.23",
    "@capacitor/core": "2.1.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/http": "^5.34.0",
    "@ionic/angular": "^5.0.6",
    "cordova-plugin-advanced-http": "^3.1.0",
    "ionic-native-http-connection-backend": "^9.0.0",
    "native-run": "^1.4.0",

**Comment by sneas** [comment]
You'll need to use `ionic-native-http-connection-backend@6.2.3`. It's the last version compatible with Angular 8.x.

**Comment by bahyusanciko** [comment]
thanks sir its works! but http native ionic not is running browser ?
![image](https://user-images.githubusercontent.com/41245088/124700938-e4c09400-df17-11eb-8d4e-82dc12b255a1.png)

**Comment by sneas** [comment]
No, Native HTTP needs Cordova.

**Comment by bahyusanciko** [comment]
thanks alot sir
