### ISSUE TITLE
Problem with android

### ISSUE THREAD

**Issue by sannaroby** [sneas/ionic-native-http-connection-backend#15]
Hello,
we're using the last plugin version and for ios devices, it's all ok.

Unfortunately, we've a problem with android devices: if we leave the NativeHttpModule and NativeHttpFallback into our application's module, we've this error posting data to the server: 

{"_body":null,“status”:599,“ok”:false,“statusText”:“Ok”,“headers”:{},“type”:2,“url”:null}

This error is only for post method (the get method works well).

What are we doing wrong?

Thanks!

**Comment by sneas** [comment]
Hi, thanks for the report. I have to investigate the issue on Android platform soon. But for now you can add this item into `providers` array of your `app.module.ts`:

```
{
  provide: NativeHttpFallback,
  useFactory: (platform: Platform, nativeHttpBackend: NativeHttpBackend, xhrBackend: XHRBackend) => {
    if (platform.is('android')) {
      return xhrBackend;
    } else {
      return new NativeHttpFallback(nativeHttpBackend, xhrBackend);
    }
  },
  deps: [Platform, NativeHttpBackend, XHRBackend]
}
```

With this code we restrict the plugin usage on Android devices. Considering CORS policy on Android is less strict comparing to iOS, the above code should be helpful in your case.

**Comment by sannaroby** [comment]
Thanks for your reply, it solves our problem: now we can 'post' from both android and ios devices! 👍

**Comment by naveenachandras** [comment]
Hi, Could you please let know if this issue was fixed or we still have to restrict the plugin usage in android? I see that even in v4.0.3, post methods are failing.

**Comment by sneas** [comment]
This plugin is depended on https://ionicframework.com/docs/native/http/
Make make sure Native HTTP is installed.
Android apps don't have the CORS issue so it's up to you, to restrict it or now. Should work both ways. I'd rather keep the Native HTTP + ionic-native-http-connection-backend in both apps in order to keep things consistent.

**Comment by keithdmoore** [comment]
In case someone else stumbles upon this from some Google sleuthing, the following worked for me in `app.module.ts`

```
{
provide: HttpBackend, useFactory:
 (platform: Platform, nativeHttpBackend: NativeHttpBackend, httpXhrBackend: HttpXhrBackend) = {
          if (platform.is('android')) {
            return httpXhrBackend;
          } else {
            return new NativeHttpFallback(platform, nativeHttpBackend, httpXhrBackend);
          }
  }, deps: [Platform, NativeHttpBackend, HttpXhrBackend]
},
```
