### ISSUE TITLE
Native HTTP does not work with cookie authorization

### ISSUE THREAD

**Issue by sefyas** [sneas/ionic-native-http-connection-backend#157]
### Subject of the issue
Native HTTP does not use cookies explicitly set

### Environment
* version of angular: `5.2.11`
* version of ionic-native-http-connection-backend: `4.0.11`
* version of @ionic/core: `5.2.11`
* version of @ionic-native/http: `4.20.0`

### Steps to reproduce
I added `NativeHttpModule`, `NativeHttpBackend` and `NativeHttpFallback` in my application's module. I also call `setCookie(url, cookie)` to set the cookie I obtain from my server (a couchDB) for all calls made through `HTTP` of `@ionic-native/http`. However, I still get unauthorized error when trying to sync data with my database. I have included simplified versions of my code below

```javascript
// app.module.ts
...
import { HTTP } from '@ionic-native/http';
import { HttpClientModule } from "@angular/common/http";
import { HttpBackend, HttpXhrBackend} from "@angular/common/http";
import { NativeHttpModule, NativeHttpBackend, NativeHttpFallback } from 'ionic-native-http-connection-backend';
...

NgModule({
  ...
  imports: [
    ...
    IonicModule.forRoot(MyApp),
    HttpClientModule,
    NativeHttpModule,
    ...
  ],
  ...
  providers: [
    ...
    HTTP,
    {provide: HttpBackend, useClass: NativeHttpFallback, deps: [Platform, NativeHttpBackend, HttpXhrBackend]},
    CouchDbServiceProvider,
    ...
  ],
  ...
})
export class AppModule {}
```

```javascript
//couchdbserviceprovider.ts
...
import PouchDB from 'pouchdb';
import PouchDBAuthentication from 'pouchdb-authentication';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { HTTP } from '@ionic-native/http';
...

@Injectable()
export class CouchDbServiceProvider {
    private db: any;
    private remote: any;
    constructor(public http: HttpClient, private httpNative: HTTP) {
        PouchDB.plugin(PouchDBAuthentication);
        this.db = new PouchDB('localdb', {skip_setup: true});
    }
    ...
    getSessionNative(credentials_){
        let url = 'URL of the couchDB database on a remote server';
        let credentials = {
          name: credentials_.username, 
          password: credentials_.password, 
        }
        let this_ = this;
        this.httpNative.post(url, credentials, {})
        .then(data => {
          let couchDBurl = 'URL of the couchDB database on a remote server';
          this_.httpNative.setCookie(couchDBurl, data['headers']['set-cookie']);
          this_.httpNative.get(couchDBurl, {}, {})
          .then(resp => { console.log('success'); })
          .catch(err => { console.log('error'); })
        })
        .catch(error => {
          console.log('error', error.status, error.headers, error.error);
        })
   }
    login(credentials) {
        this.getSessionCookie(credentials);

        let couchDBurl = 'URL of the couchDB database on a remote server';
        this.remote = new PouchDB(couchDBurl); 
        this.remote.logIn(credentials.username, credentials.password, function (err, response) {
              if (err) { concole.log('login error') }
              else {
                  let options = { live: true, retry: true, continuous: true };
                  this.db.sync(this.remote, options).on('error', (err_) => { console.log('sync error')});
              }
        })
    }
    ...
}
```

### Expected behaviour
Given this library is designed to have `HttpClient` use `NaiveHTTP` and I'm setting cookie for native http, I was expecting http requests through HttpClient go through using the cookie I have set.

### Actual behaviour
All HttpClient requests get unauthorized error in response even after running setCookie to allow authorization.

**Comment by sneas** [comment]
Hey, I've just checked out the cookie thingy, and it's working correctly on this example https://github.com/sneas/ionic-5-http-test/blob/issue-157/src/app/tab1/tab1.page.ts

I receive the cookie back from the server in both cases.

Tbh, I'm misunderstanding the necessity of this library in your particular case. The purpose of this library is to never use NaiveHTTP explicitly in your Ionic app. The benefits of this library got lost as soon NaiveHTTP is used explicitly, imho. But I might miss the context 💁‍♂️
