### ISSUE TITLE
@ionic-native renamed to @awesome-cordova-plugins

### ISSUE THREAD

**Issue by jkorrek** [sneas/ionic-native-http-connection-backend#158]
### Subject of the issue
Last September, the @ionic-native plugins (including @ionic-native/http) were transferred out of the Ionic organisation into the community & renamed to @awesome-cordova-plugins.
As far as I understand it the "old" @ionic-native plugins will still be accessible (at least for the next two years), but any further updates will be publish under @awesome-cordova-plugins.
Source: https://ionicframework.com/blog/a-new-chapter-for-ionic-native/

As ionic-native-http-connection-backend currently depends on @ionic-native/http, any apps using are kind of stuck in the update / change to the packages.
Do you think that ionic-native-http-connection-backend should switch to using @awesome-cordova-plugins/http? From everything I have seen so far, only the (peer) dependency, imports and maybe documentation would need to be update.
If this is a change you are willing to make, I would be happy to provide / help with a Pull Request for these changes.

### Environment
-

### Steps to reproduce
-

### Expected behaviour
-

### Actual behaviour
-

**Comment by sneas** [comment]
Thank you for raising this issue, Johannes 👍 I wasn't aware of the ionic-native reorg. This is definitely something that has to be addressed and your help will be much appreciated.
