### ISSUE TITLE
Custom Content-Type always leads to the data attempting to be parsed as if its url encoded

### ISSUE THREAD

**Issue by cleavera** [sneas/ionic-native-http-connection-backend#168]
### Subject of the issue
When making a request that has an unknown or custom content type where the body of the request is a string. The body is always parsed into an object and sent as if it was urlencoded. This ends up with the request body being mangled.

Our specific use case is where we're making an odata batch request, this requires the content type to be set to 'Content-Type': `multipart/mixed; boundary=odata_batch`. Our request body is
```
--odata_batch
Content-Type: application/http
Content-Transfer-Encoding: binary

GET learningRequests?$count=true&$filter=RequestStatus%20eq%20'NOT_REPLIED' HTTP/1.1
Accept: application/json

--odata_batch--
```

Due to this code here
https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/utils/detect-serializer-and-data.ts
The fallback ends up being that the data is run through `bodyToObject` which trys to convert the body to an object of url encoded params, this mangles the request body.

Some potential options for fixes.
1. The fallaback is instead that the string body is proved as is and the serialiser set to utf8 (Not sure what the side effects of this would be, presumably urlencoded was chosen as the fallback for good reason).
2. Add odata as a special case in that code (This doesn't seem like the best solution and would need to be extended everytime someone comes up with a new content type)
3. Allow some sort of configuration object to be passed in to map custom content types to specific behaviours. 

Exploring option 3 as I think this could be the best solution:

We could use the forRoot pattern to configure this while maintaining compatibility of NativeHttpBackend with HttpBackend. Something like this:
```
@NgModule({
  imports: [
    HttpClientModule,
    NativeHttpModule.forRoot({
        contentTypeSerialisers: [
            (req: HttpRequest<any>) => {
                if (req['Content-Type'] === 'multipart/mixed; boundary=odata_batch') {
                     return {
                         serializer: 'utf8',
                         data: req.body,
                     };
                }

                return null;
            }
        ]
    }]
  ],
  providers: [
    {
      provide: HttpBackend,
      useClass: NativeHttpFallback,
      deps: [Platform, NativeHttpBackend, HttpXhrBackend]
    }
  ]
})
export class AppModule {}
```

### Environment
* version of angular : 13.3
* version of ionic-native-http-connection-backend : 10.0
* version of @ionic/angular : 6.1
* version of @awesome-cordova-plugins/http : 5.43

**Comment by sneas** [comment]
Hi Anthony, thank you for the accurately-described issue. The fix has just been released. From now on, `multipart/mixed` requests are going to be handled by `utf8` serializer. This should align `ionic-native-http-connection-backend` with `XHR`/`HttpClient` behavior.

**Comment by cleavera** [comment]
Perfect, thanks very much @sneas !
