### ISSUE TITLE
Angular 4 HttpClient

### ISSUE THREAD

**Issue by monkeychops** [sneas/ionic-native-http-connection-backend#20]
Hi there,

Firstly I'd like to start by saying thanks for writing such an awesome plugin, it really got me out of a jam! 

Was just wondering if you plan to update it to use angular 4 HttpClient.

Thanks

**Comment by sneas** [comment]
Hi @monkeychops, thanks for nice words :) The plan is to upgrade the plugin this week. Weekend, probably.

**Comment by monkeychops** [comment]
That's amazing news! I'm writing an ionic 2 app using apollo client. I've just upgraded apollo and the new version uses HttpClient rather than Http so running into those annoying CORS issues again.

Look forward to the update 👍

**Comment by sneas** [comment]
Done with #21

**Comment by monkeychops** [comment]
Legend!
