### ISSUE TITLE
Json Parse Error on HTTP Post

### ISSUE THREAD

**Issue by ycbayrak** [sneas/ionic-native-http-connection-backend#26]
I've working HTTP services for my API on Ionic side. It's working when i'm testing on browser with `ionic serve`  or testing on native android device without this plugin.
After installed this plugin GET methods works with no problem but, POST methods that contains data returns JSON parse errors from server.

**Comment by sneas** [comment]
Hi, thank you for opening the issue. Can you please provide an example of request which works in browser and android app but not with the plugin?

Eg

```
const postData = {
  data
};

const requestOptions = {
  ...options
};

this.httpClient.post(url, postData, requestOptions);
```

**Comment by sneas** [comment]
Closing due to insufficient information provided.
