### ISSUE TITLE
How to use this plugin in Ionic 1?

### ISSUE THREAD

**Issue by malwatte** [sneas/ionic-native-http-connection-backend#28]
I am still using Ionic 1(1.3.5)
It uses angular version 1.5.3.

How do I use this plugin?

Thanks,

**Comment by sneas** [comment]
The plugin doesn't work with Angular < 2.
You probably could consider going back to UIWebView.

**Comment by malwatte** [comment]
UIWebView not working properly in iPhone X. Issues in safe area when device rotated.
Looks like I have to use Cordova http plugin.
:(

**Comment by sneas** [comment]
Uhhh, looks like using Cordova plugin is the only option so :(
Unless you can tweak the server to respond with the right header.
