### ISSUE TITLE
Ionic view app compatibility?

### ISSUE THREAD

**Issue by romain10009** [sneas/ionic-native-http-connection-backend#29]
Hi, great job. Does this work with the ionic view app (blue icone, the new one). Since it is a native cordova plugin I suppose it does not?

**Comment by sneas** [comment]
This lib is based on Cordova plugin https://github.com/silkimen/cordova-plugin-advanced-http

The plugin is listed as supported by Ionic View https://ionicframework.com/docs/pro/view.html#plugin-support

It should work.
