### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by aces2808** [sneas/ionic-native-http-connection-backend#30]
Hi,

I have already defined the module on the AppModule, I was looking for and example on how to use it on making any http request, haven't seen any. On my project I use the HttpClient for authentication and Native Http for the succeeding.

Cheers

**Comment by sneas** [comment]
The library is the bridge between HttpClient and Native HTTP. It provides HttpBackend interface to HttpClient so you don't have to inject Native HTTP service explicitly. The library will route all the HttpClient's requests to Native Http in the background.

The usage instructions can be found in the [README](https://github.com/sneas/ionic-native-http-connection-backend).

All you have to do is to enable the library in AppModule and use HttpClient as there are no any troubles with CORS. The library will do all the dirty work of understanding whether you have Native HTTP or you're in the browser and do requests with the help of Native HTTP whenever it's possible.
