### ISSUE TITLE
Issue while calling an API 

### ISSUE THREAD

**Issue by impavan** [sneas/ionic-native-http-connection-backend#31]
Hi there,

I am getting a wierd error when I try to call an API. Can you help me to fix the issue. The issue is 

TypeError: (/^[?#]/.test(query) ? query.slice(1) : query) .split is not a function. (In '(/^[?#]/.test(query) ? query.slice(1) : query) .split('&')', '(/^[?#]/.test(query) ? query.slice(1) : query) .split' is undefined)
getBodyParams — native-http-backend.js:109
(anonymous function) — native-http-backend.js:37
_trySubscribe — Observable.js:171
subscribe — Observable.js:159
subscribe — Observable.js:156
subscribe — Observable.js:156
callToLoginAPI — existing-user-login.ts:72
(anonymous function)
callWithDebugContext — core.es5.js:13486
(anonymous function) — core.es5.js:9226
(anonymous function) — platform-browser.es5.js:2651
onInvokeTask — core.es5.js:3881
runTask — polyfills.js:3:10225
invokeTask — polyfills.js:3:16182
p — polyfills.js:2:27000
v — polyfills.js:2:27240.

Any help in this regard will be very great.

**Comment by impavan** [comment]
Here is my code. I have created a ServiceWorker and i have created the following method.
userLogin(phoneNum: string) {
    let userData = new FormData();
    userData.append('BrandURLID', BRAND_ID);
    userData.append('IdetentifierKey', 'mobile');
    userData.append('IdetentifierValue', phoneNum);
    userData.append('NotificationType', 'mobile');
    userData.append('lang_code', 'en');
    // userData.append('device_id', localStorage.getItem('push_token'));
    // userData.append('device_type', localStorage.getItem('model'));
    // userData.append('device_version', localStorage.getItem('version'));
    let body = userData;
    return this.http.post(BASE_URL + LOGIN, body, { headers: this.auth.getHeader() })
      .do((res: Response) => res)
      .map((res: Response) => res.json());
  }

Now I am subscribing for the data in login page as shown below.

this.userProvider.userLogin(this.mobNumData).subscribe(data => {
        if (data) {
            console.log(data);
        }
      }, err => {
        console.log(err,'=====================+Error==============================');
      });


But now I am getting the following error message when I try to hit the API.

TypeError: (/^[?#]/.test(query) ? query.slice(1) : query) .split is not a function. (In '(/^[?#]/.test(query) ? query.slice(1) : query) .split('&')', '(/^[?#]/.test(query) ? query.slice(1) : query) .split' is undefined)
getBodyParams — native-http-backend.js:109
(anonymous function) — native-http-backend.js:37
_trySubscribe — Observable.js:171
subscribe — Observable.js:159
subscribe — Observable.js:156
subscribe — Observable.js:156
callToLoginAPI — existing-user-login.ts:72
(anonymous function)
callWithDebugContext — core.es5.js:13486
(anonymous function) — core.es5.js:9226
(anonymous function) — platform-browser.es5.js:2651
onInvokeTask — core.es5.js:3881
runTask — polyfills.js:3842
invokeTask — polyfills.js:3984
p — polyfills.js:3193
v — polyfills.js:3206

**Comment by sneas** [comment]
Hi @impavan, thanks for opening the issue. I was not able to reproduce the exact issue but I found a number of problems in using FormData object with the library. Going to update the library when I get less busy. Hopefully this or the next week.
