### ISSUE TITLE
Cordova Not Available error

### ISSUE THREAD

**Issue by anjildhamala** [sneas/ionic-native-http-connection-backend#43]
This is not really an issue but more of a question. 
Do I inject ionic-native HTTP or Angular's HttpClient in my service? From the looks of the README.md, it shows that we need to inject ionic-native HTTP. However, I'm getting cordova_not_available error while serving the app in browser, as in `ionic serve`. Would be great if you could post a small single http call tutorial.

**Comment by sneas** [comment]
Hi, you have to update `app.module.ts` as described [here](https://github.com/sneas/ionic-native-http-connection-backend#httpclientmodule-angularcommonhttp).

After this you can transparently inject Angular's `HttpClient` into your services.

**Comment by anjildhamala** [comment]
Thank you for replying,. I have followed every last detail that's in the readme. Hence, I have the app.module.ts set up as instructed. 
Forgive me for I do not understand the injection part. Can I change the injection from HTTP to HttpClient and vice versa? Wouldn't that mean I'll have to change my service calls to cater to that specific http implementation? For example, HTTP returns promises while HttpClient returns Observables. the parameters pattern in the service calls are different for both implementation. Could you please clarify this for me? I've been trying to fix this Webkit cors issue on iOS for past week and your plugin seems like the only saving grace for me.

**Comment by anjildhamala** [comment]
https://github.com/sneas/ionic-native-http-connection-backend#i-followed-the-installation-and-usage-instructions-but-still-experience-cors-issues-on-device

This instruction imports native HTTP and that threw me off. I injected HttpClient in my service and your plugin was smart enough to use native HTTP in an actual device. Thanks for this awesome bridge.

**Comment by sneas** [comment]
The intention of the library is to let users to never use HTTP services in their code because HTTP service works correctly only on device/simulator but not in browser.

All you have to to is to update your `app.module.ts` in accordance with README. After that you can inject `HttpClient` service in you code and it will be working properly in both environments: browser and device/simulator.
