### ISSUE TITLE
does it work with httpInterceptor

### ISSUE THREAD

**Issue by ogomaemmanuel** [sneas/ionic-native-http-connection-backend#45]

**Comment by sneas** [comment]
Yes it does.

**Comment by sneas** [comment]
Just modify your app.module.ts in accordance with [this section](https://github.com/sneas/ionic-native-http-connection-backend#httpclientmodule-angularcommonhttp).

Don't forget to [install it](https://github.com/sneas/ionic-native-http-connection-backend#installation) first.

In case it still isn't working, [this section](https://github.com/sneas/ionic-native-http-connection-backend#i-followed-the-installation-and-usage-instructions-but-still-experience-cors-issues-on-device) can help you to debug your app.
