### ISSUE TITLE
I followed installation and usage instructions but still receive CORS issue on browser.

### ISSUE THREAD

**Issue by ildarnm** [sneas/ionic-native-http-connection-backend#46]
Hi, 
As I understand, if I run the application on the browser (Chrome on Windows) by the command ```ionic cordova run browser``` and make POST request then I shouldn`t receive CORS issue, but I receive.

angular 5.2.9
ionic-native/http 4.7.0
ionic-native-http-connection-backend 4.0.7

**Comment by sneas** [comment]
Hi,
The intention of the library is to provide transparent CORS issue solution on device. To solve CORS problem when running `ionic cordova run browse` please follow **The Ionic CLI proxy server** section of this article https://blog.ionicframework.com/handling-cors-issues-in-ionic/

**Comment by ildarnm** [comment]
Thanks for clarifying and and one more question: Will the ionic-native-http-connection-backend work inside Ionic View App or only inside native app?

**Comment by sneas** [comment]
The idea of this library is to provide an ionic-native adapter for HttpClient. If ionic-native could not be used for any reason the library falls back to XmlHttpRequest. Is should work everywhere.
