### ISSUE TITLE
fail to handle unhandled response from server

### ISSUE THREAD

**Issue by jhaankit** [sneas/ionic-native-http-connection-backend#47]
If the request is not handled at server end then response comes as some html content with "bad request".
But plugin fails to handle it and http.get method never goes to error callback.

**Comment by jhaankit** [comment]
I am sorry, i investigated further and found that the error callback is working fine.
Only the missing element is url, which looks fine.
Hence i am closing my ticket.
<img width="329" alt="screen shot 2018-07-10 at 7 31 11 pm" src="https://user-images.githubusercontent.com/11736703/42515012-597b35e6-8478-11e8-8d24-ab69c385893d.png">

**Comment by sneas** [comment]
The missing URL is the known problem of https://github.com/silkimen/cordova-plugin-advanced-http. If you're missing on this bit, please go ahead and create an issue in `cordova-plugin-advanced-http` project.
