### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by UlisesCeca** [sneas/ionic-native-http-connection-backend#48]
I'm not sure if I understood how this plugin works.

I understand that you just do `.get` and it solves for you wether youre on browser or mobile

So my question is (since in the examples you use Angular and the Native in other place) should I use `this.http.get(...)` (assuming this is Angular) or `this.httpNative.get(...)` (assuming this is the native plugin)

Thanks

**Comment by joeyscarim** [comment]
I use `this.http.get(...)` in my Angular calls with this plugin imported and passed to my `providers` in `app.module.ts` and have no issues. I do this for iOS builds only.

**Comment by tomriddle1234** [comment]
This should be put on README, it's confusing without explainations.
