### ISSUE TITLE
this.http.get is not a function

### ISSUE THREAD

**Issue by SimBrunet** [sneas/ionic-native-http-connection-backend#49]
Hi everyone, 
I had some Http issues lately with iOS and I found this plugin. 
I installed it and add the imports in my app.module.ts as written in the READ.me but when I try to run my app on the browser (ionic serve) I got the following error : 
this.http.get is not a function. 

I have declader Http as a HttpClient component, is it correct or should I change it because of the pluggin ? 
It worked fine before these modifications on browser.

**Comment by sneas** [comment]
Hi @SimBrunet, [these are the app.module.ts modifications for Angular > 4.3](https://github.com/sneas/ionic-native-http-connection-backend#httpclientmodule-angularcommonhttp). You have to inject HttpClient to make it work.

**Comment by SimBrunet** [comment]
Thank you for your quick answer @sneas, I did these modifications and now it works ! 
Thank you for your plugin !
