### ISSUE TITLE
Please add a @NgModule annotation error when running --prod build

### ISSUE THREAD

**Issue by richardshergold** [sneas/ionic-native-http-connection-backend#5]
Hi

When I try a Production build with --prod I get the following error:

`Error: Unexpected value 'NativeHttpModule in /Users/richardshergold/Ionic Projects/myApp/node_modules/ionic-native-http-connection-backend/dist/native-http-module.d.ts' imported by the module 'AppModule in /Users/richardshergold/Ionic Projects/myApp/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by sneas** [comment]
Hi @richardshergold, you probably are using the outdated version of the library. Please try v1.2.4. The error should be gone.

**Comment by richardshergold** [comment]
Great, thanks - that fixed it.

**Comment by Vatsalya-singhi** [comment]
Hi, Please check the issue posted at [https://github.com/nstudio/xplat/issues/149](url)
Thank you.
