### ISSUE TITLE
What exactly does it do and how?

### ISSUE THREAD

**Issue by janpio** [sneas/ionic-native-http-connection-backend#53]
This looks like a thing to make `HttpClient` use `@ionic-native/http`.

Could you explain a bit _what_ exactly it does internally and how? Does it just switch between normal http and Ionic Native based on platform? Maybe add that to the readme? 

How does the [troubleshooting part](https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md#i-followed-the-installation-and-usage-instructions-but-still-experience-cors-issues-on-device) work? On first sight this is just testing if @ionic-native/http is correctly installed and usable. Did I miss anything?

**Comment by sneas** [comment]
Hi @janpio, thanks for pointing this out. Seeing the number of "how to use the library?" and "i don't understand what I'm doing" issues the library suffers of misleading documentation. I made several attempts to improve the situation but apparently it didn't help...

Briefly:
1. The library provides `HttpBackend` interface for Angular's `HttpClient`
2. `HttpBackend` interface  tries to use Ionic's Native `HTTP` service whenever it is possible (it is possible on device only)
3. If `HttpBackend` finds it impossible to use Ionic's Native `HTTP` it falls back to standard `HttpXhrBackend` (which uses `XmlHttpRequest`)

This strategy allows developers to use Angular's `HttpClient` transparently in both environments: Browser and Device.

The library DOES NOT solves CORS issues in browser. The browser's CORS issues could be solved with the help of this article https://blog.ionicframework.com/handling-cors-issues-in-ionic/.

**Comment by janpio** [comment]
>If HttpBackend finds it impossible to use Ionic's Native HTTP it falls back to standard HttpXhrBackend (which uses XmlHttpRequest)
Is this how Angular's `HttpClient` normally works? Does it switch back to default behaviour?

Let's brainstorm a new README introduction:

- Ionic uses WKWebView by default
- WKWebView does CORS stuff, which may cause problems for apps
- Normal http requests with Angular trigger it (which didn't happen before with UIWebView)
- Real solution: Fix it on the server side
- Alternative solution: Use @ionic/native's http
- Problem: Only works on device
- Solution: This library!
- Patches Angular's http to use @ionic/native's http if one device, keeps default behavior when @ionic-native is not available (in browser)

All correct?

**Comment by sneas** [comment]
> Is this how Angular's HttpClient normally works? Does it switch back to default behaviour?

No, Angular uses `HttpXhrBackend` by default and never switches by itself.

The switching in the context of library is provided by `NativeHttpFallback` class which decides whether to use `NativeHttpBackend` (the `HttpBackend` interface adaptor of Native `HTTP` service to `HttpClient`) or falls back.

> All correct?

Precisely!

**Comment by janpio** [comment]
> No, Angular uses HttpXhrBackend by default and never switches by itself.

Yeah, that's what I meant: If `@ionic/native` is not present, it lets Angular's http do its default thing.

So this library basically makes Angular's http use @ionic/native's http on devices, but keeps it unchanged in the browser and everywhere @ionic/native is not available.

**Comment by sneas** [comment]
That's exactly what the library does.
