### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by MohamedFekry007** [sneas/ionic-native-http-connection-backend#54]
Appreciate your support please, when try to make API calls, its fails as the cross origin issue as below.

Failed to load resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin

**Comment by sneas** [comment]
Hi @MohamedFekry007 

1. You can refer to this article if you experience CORS issue in browser https://blog.ionicframework.com/handling-cors-issues-in-ionic/
2. You can refer to https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md if you experience CORS issue on device

**Comment by MohamedFekry007** [comment]
Nothing in safari console but i got the below from Xcode console.

CDVPlugin class CordovaHttpPlugin (pluginName: CordovaHttpPlugin) does not exist.
ERROR: Plugin 'CordovaHttpPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
FAILED pluginJSON = ["CordovaHttpPlugin533358542","CordovaHttpPlugin","post",["https:\/\/httpbin.org\/post",{"a":"b"},"urlencoded",{"Cookie":""},60]]

**Comment by sneas** [comment]
Probably, CordovaHttpPlugin and/or Ionic Native HTTP is not installed or incorrectly installed.

You can follow installation steps from the documentation https://ionicframework.com/docs/native/http/

**Comment by MohamedFekry007** [comment]
i got another error now.

error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.

**Comment by sneas** [comment]
Hmmm. I can't find JSON.stringify() in the library's code. Probably you get this error from somewhere else.

**Comment by MohamedFekry007** [comment]
ok, thanks will check.
