### ISSUE TITLE
Falling back to XmlHttpRequest only on certain requests.

### ISSUE THREAD

**Issue by TehCrucible** [sneas/ionic-native-http-connection-backend#58]
Here's a curly one for you. In my current app I'm seeing a strange issue where only "some" requests fallback to XmlHttpRequest and others are transported through Native Http fine.

The weird thing is, there's nothing strange about the requests. They're both relatively normal GET requests. Ostensibly, the only difference I can see is the URLs to which they are going.

I realize I'm not giving you much to go on here, but is there any reason you can see that one GET request might be transported through native and another might not?

**Comment by sneas** [comment]
Hi, here is the code responsible for routing requests through NativeHTTP or falling back to XmlHttpRequest

https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/native-http-fallback.ts

The reasons for falling back:
1. NativeHTTP can not be detected (probably not the case)
2. The request is recognized as local: http(s):// part of an URL is missing. Could it be the reason in your case?

**Comment by TehCrucible** [comment]
Perfect, that will do it. Turns out it was a simple typo, with a space being inserted before the `https://` part. Obviously that was enough to throw it off. Thanks for your help.
