### ISSUE TITLE
AOT build error

### ISSUE THREAD

**Issue by ArikEpstein** [sneas/ionic-native-http-connection-backend#63]
HttpBackend provider not provided on AOT build.

**Comment by sneas** [comment]
Can clarify on this please?

**Comment by ArikEpstein** [comment]
I'm using ionic 4 And angular version 7.1.3 
I try to se this library and it working great and excellent

The problem is when i try production build.
the build is success but for some reason the angular aot build overidde the httpBackend provider to default provider.
And I could not get it working.
I google for this issue 
and this is the only thing i found 
close to it.
https://github.com/angular/angular/issues/11178
I'm looking for help.
Maybe change the useClass to factory 
will help me or ?

**Comment by sneas** [comment]
Did you install `ionic-native-http-connection-backend@next`, https://ionicframework.com/docs/native/http/, and followed https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md ?

**Comment by ArikEpstein** [comment]
Hi @sneas 
Thank you for your quick response.

I reinstall and go over all the steps.
And again this library working perfect and excellent
on JIT build and fail with AOT build.

I try also the TROUBLESHOOTING in AOT 
And i get the log - 'cordova-plugin-advanced-http is installed properly'.

Something on AOT build is override the HttpBackend provider
OR ... ?

**Comment by sneas** [comment]
Hi @ArikEpstein,

I've just created this project https://github.com/sneas/ionic-4-http-test to test the library with Ionic 4 and AOT. And I'm quite confident it works as expected.

The `ios` folder already contains the project compiled with `prod` flag. You can run `npx cap open ios` to open project with XCode and after that you can run it you can give it a try with device or simulator.

The current `ios` folder contains slightly modified version of `ionic-native-http-connection-backend` which logs into console `Open with cordova` message in case `ionic-native-http-connection-backend` uses corodave plugin do perform HTTP calls.

You can see the request example in `AppComponent`.

You can also try to `npm run prod` to rebuild the project with `--prod` flag and open it with xcode. Unfortunately after rebuilding `ios` folder content would be overwritten and `Open with cordova` message will be gone. But you can still make sure the app still performs calls through cordova's plugin by absence of any specific XHR activity in Network tab of Safari Developer Tools:

![image](https://user-images.githubusercontent.com/144651/50041592-b3c99c80-0057-11e9-9d64-3826f8158b7d.png)

Also you may check `packages.json` to see installed version of `@ionic-native/http`. And see the way project initialized in `AppModule`.

I hope this will help to solve your problem. Good luck!

**Comment by sneas** [comment]
Ah I also have to mention the plugin falls back to XHR when the HTTP request does not contain absolute URL started with http or https. This is the limitation of `cordova-plugin-advanced-http` which doesn't like relative URLs.

You can have a look at at the fallback implementation here https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/native-http-fallback.ts#L27

**Comment by ArikEpstein** [comment]
Hi @sneas

Thank you very much
On the test project .

What that i found,
That i have a singleton service that make my httpClient calls,
With @Injectable({
  providedIn: 'root'
})

I remove the built in provideIn from the service
And Inject it in the providers array in my sub module

This fix my AOT build.
