### ISSUE TITLE
Can't install with latest @ionic-native/http 5.0.0

### ISSUE THREAD

**Issue by tallcoder** [sneas/ionic-native-http-connection-backend#67]
I am having to upgrade packages because of the need to use the native/camera plugin, which is forced at the latest 5.0.0. With that, I can't upgrade or keep this plugin installed because of this: 

> ionic-native-http-connection-backend@4.0.9 requires a peer of @ionic-native/http@^4.4.2 but none is installed.

I'm going to work on removing it, but it would have been much easier to just upgrade to use with latest ionic http plugin.

**Comment by sneas** [comment]
Have you tried to install `ionic-native-http-connection-backend@next` ?

**Comment by sneas** [comment]
`ionic-native-http-connection-backend@next` depends on `@ionic-native/http@5.0.0-beta.21` though. Updating dependencies in [package.json](https://github.com/sneas/ionic-native-http-connection-backend/blob/master/package.json) might fix the issue.

**Comment by dasider41** [comment]
The package doesn't work with ionic v3 and ionic-native/http 5.0.0.
The error message shows `Cannot find name 'HTTP'.` in `/dist/http/native-http-backend.d.ts`.

**Comment by sneas** [comment]
ionic-native-http-connection-backend@4.1.0 supporting ionic@3 + ionic-native@5 has been released
