### ISSUE TITLE
Set Native Http data serialezer based on Angular's HttpClient serialzer

### ISSUE THREAD

**Issue by kevin-barrientos** [sneas/ionic-native-http-connection-backend#68]
I'm trying to consume a SOAP service but the server fails to process it as _"The servcer cannot service the request because the media tipo is unsupported"_ I can consume it from the web with Angular's HttpClient but once I compile and  start using NativeHttp it won't let me. 

As stated on this [issue](https://github.com/silkimen/cordova-plugin-advanced-http/issues/34), Native Http now supports to set the data serializer to 'utf-8' so the body is not changed. 

Is there a way to change this properti trhrouh the plugin?

**Comment by sneas** [comment]
8d6177a2576e57b2faa33839f6a54d1bb0f923c8 should solves the issue. The new version `5.0.3` has just been released. All you have to do while making a request with HttpClient is to set the content type which starts with `text/`. `text/plain; charset=UTF8` can work. Or `text/xml`. The library will automatically set necessary serializer.
