### ISSUE TITLE
Issue when having a self signed certificate in the server

### ISSUE THREAD

**Issue by anirajkumar-enoah** [sneas/ionic-native-http-connection-backend#72]
Hi

Getting issue when the server app is having a self signed certificate in that case how to set the ssl pinning or nocheck?

Thanks

**Comment by sneas** [comment]
Hi, I've never dealt with self-signed certificates, but probably calling

```
this.HTTP.setSSLCertMode('pinned')
```

on app's startup will help.

Here is the example of injecting HTTP service: https://ionicframework.com/docs/native/http#usage

**Comment by sneas** [comment]
Closing the issue since no reply has been given. Feel free to reopen.
