### ISSUE TITLE
Remove @angular/http 

### ISSUE THREAD

**Issue by danielsogl** [sneas/ionic-native-http-connection-backend#74]
Angular 8.0.0 (released today) drops the `@angular/http` package. The library should be rewritten to support ionics coming Angular 8 support.

**Comment by buko106** [comment]
When I remove `@angular/http` from my ionic4 app , I replace

```typescript
import { NativeHttpBackend, NativeHttpFallback, NativeHttpModule } from 'ionic-native-http-connection-backend';
```

with

```typescript
import { NativeHttpModule } from 'ionic-native-http-connection-backend/dist/native-http-module';
import { NativeHttpBackend } from 'ionic-native-http-connection-backend/dist/native-http-backend';
import { NativeHttpFallback } from 'ionic-native-http-connection-backend/dist/native-http-fallback';
```

This suppresses compile error.

One possibility is separating modules for `@angular/http` from index.d.ts

**Comment by sneas** [comment]
Hi guys, thank you for the issue. Will fix it as soon as I get back from vacation the next week.
