### ISSUE TITLE
Angular dependecies

### ISSUE THREAD

**Issue by saoron** [sneas/ionic-native-http-connection-backend#8]
Hi, 
I suggest keep the Angular version compatible with the **current** recommended ionic version (4.1.3)

**Comment by sneas** [comment]
Good idea. But are you experiencing any troubles because of it?

**Comment by saoron** [comment]
Yes, npm will not install v2.0 because of this.

**Comment by sneas** [comment]
v2.0.1 should fix the issue.

**Comment by saoron** [comment]
Great, Thanks!

**Comment by sneas** [comment]
feel free to close the issue if it's fixes
