### ISSUE TITLE
Incorrect body value is returned when responseType is not supported

### ISSUE THREAD

**Issue by ippeiukai** [sneas/ionic-native-http-connection-backend#80]
version: 5.0.4
related to #25

This backend do not support `responseType` such as `'blob'`.

However, the current behaviour is the resulting response body having value of wrong type, rather than this Backend throwing an error or otherwise notifying devs that unsupported responseType is specified. That makes debugging very hard.

WIth `observe: 'body'`, HttpClient throws an error. However, it is thrown by HttpClient and is still hard for a dev to notice that the issue is in the backend.
https://github.com/angular/angular/blob/7.2.15/packages/common/http/src/client.ts#L515

**Comment by sbchopade** [comment]
Did you find any solution?

**Comment by ippeiukai** [comment]
We’ve always used injector.create to specify different backend when blob response is needed. This ticket is about debbagability when mistake was made.

Have you tried new version of http advanced? It seems blob might just work. We are intending to try it out when we have a spare time.
https://github.com/silkimen/cordova-plugin-advanced-http/issues/171

**Comment by ippeiukai** [comment]
I gave cordova-plugin-advanced-http@2.1.1 a try, but responseType blob didn't work.

- "ionic-native-http-connection-backend": "5.0.4"
- "@ionic-native/http": "5.10.0"
- "cordova-plugin-advanced-http": "2.1.1"

**Comment by ippeiukai** [comment]
@sbchopade 
We use following provider. Whenever we need to do something this library does not work, we inject `XhrHttpClient` instead of `HttpClient`.

```TS
export type XhrHttpClient = HttpClient;
export const XhrHttpClient = class XhrHttpClient extends HttpClient {};

export function xhrHttpClientFactory(httpXhrBackend: HttpXhrBackend): XhrHttpClient {
  return Injector.create([
    { provide: HttpClient, useClass: HttpClient, deps: [HttpHandler] },
    { provide: HttpHandler, useValue: httpXhrBackend },
  ]).get(HttpClient);
}

export const XHR_HTTP_CLIENT_PROVIDER = {
  provide: XhrHttpClient,
  deps: [HttpXhrBackend],
  useFactory: xhrHttpClientFactory,
};
```

Switching is not automatic, and as I mentioned above, when a dev forgets to use XhrHttpClient, the native app errors with no indication the http backend is in fault.
Also, this hack is only useful to you if you need Blob for particular resources that does not require native backend. We use XhrHttpClient only for downloading some binary files that do not need CORS.

**Comment by sneas** [comment]
Hi guys, sorry for the late response. Accidentally unwatched the repo and haven't seen notifications for awhile 😬

Thank you for the issue. Didn't know of the recent `cordova-plugin-advanced-http` updates.

Looks like `cordova-plugin-advanced-http` guys have not only added blob support but also `sendRequest` method (the proper way to receive blob data).

Bringing in blob support will require a bit of refactoring and testing of the existing library. I'm on it but can not provide any estimates about the delivery.

What I am sure about is the blob support will be released under `@next` tag and it will be version `6.x.x`.  Meanwhile you'd rather take care of upgrading your library's version from 5.0.4 to 6.1.0 (the latest). The upgrade should go smoothly unless you're still using `@angular/http` module.

**Comment by raukouski** [comment]
> @sbchopade
> We use following provider. Whenever we need to do something this library does not work, we inject `XhrHttpClient` instead of `HttpClient`.
> 
> ```ts
> export type XhrHttpClient = HttpClient;
> export const XhrHttpClient = class XhrHttpClient extends HttpClient {};
> 
> export function xhrHttpClientFactory(httpXhrBackend: HttpXhrBackend): XhrHttpClient {
>   return Injector.create([
>     { provide: HttpClient, useClass: HttpClient, deps: [HttpHandler] },
>     { provide: HttpHandler, useValue: httpXhrBackend },
>   ]).get(HttpClient);
> }
> 
> export const XHR_HTTP_CLIENT_PROVIDER = {
>   provide: XhrHttpClient,
>   deps: [HttpXhrBackend],
>   useFactory: xhrHttpClientFactory,
> };
> ```
> 
> Switching is not automatic, and as I mentioned above, when a dev forgets to use XhrHttpClient, the native app errors with no indication the http backend is in fault.
> Also, this hack is only useful to you if you need Blob for particular resources that does not require native backend. We use XhrHttpClient only for downloading some binary files that do not need CORS.

Could you please specify where should we provide XHR_HTTP_CLIENT_PROVIDER and how to call to the server throughout XhrHttpClient now?
