### ISSUE TITLE
How to handle error?

### ISSUE THREAD

**Issue by rajamuthur** [sneas/ionic-native-http-connection-backend#82]
Thanks for the awesome plugin.

ionic info details:
Ionic:
   ionic (Ionic CLI)  : 4.11.0 (C:\Users\rajamuthu.ramasamy\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:
   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

System:
   Android SDK Tools : 26.1.1 (D:\android-sdk\)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.8.0
   OS                : Windows 8.1

Getting error status as -1 or -2 or -3 or 0 instead of HTTP error codes like 404, 500, 413.
Sample error response:
name: "HttpErrorResponse"
ok: false
status: -3
statusText: "Unknown Error"

I got confused why am getting error status as -1 or -2 or -3 or 0.

**Comment by sneas** [comment]
Hi, you're right, this looks odd. The library does not do http response status conversion. It takes http response status provided by https://github.com/silkimen/cordova-plugin-advanced-http. So the problem should be solved on that side. Do you know any way of reproducing the problem with https://httpbin.org/ or any other public request and response service?

**Comment by sneas** [comment]
Closing for now. Feel free to reopen with more details to reproduce the issue.
