### ISSUE TITLE
Not working in android 4.4.2

### ISSUE THREAD

**Issue by rajamuthur** [sneas/ionic-native-http-connection-backend#83]
This plugin not working in devices which has version 4.4.2

https://github.com/sneas/ionic-native-http-connection-backend/blob/d0ce91a7915223d2a535bd1a10fea7116456ee2a/src/native-http-backend.ts#L47

ES6 partially supported in android device 4.4.2

**Error:** advanced-http value must be string

Could you please provide the alternative?

It's working fine when I have used as

`var headers = {};`

**Comment by sneas** [comment]
Sorry for the late response. Accidentally unwatched the repo. Could you please provide more details on the ways to reproduce the error and how you fix it in your code?

**Comment by rajamuthur** [comment]
Hi,
Issue reproduced when try to send values in the header

Example:
in my case am trying to send api token

```
reqOpts = {
        params: new HttpParams(),
        headers: new HttpHeaders()
      };
reqOpts.headers = reqOpts.headers.append('HTTP_X_SP_APIKEY', <API_KEY>);

this.http.get(<URL>, reqOpts);
```

Please find the attachment for the error
![Error](https://user-images.githubusercontent.com/10390662/64853726-a880bd00-d639-11e9-92e5-a9b636a3b4ee.png)


**ionic-native-http-connection-backend/src/native-http-backend.ts**

Line 47 in d0ce91a
`const headers = new Map<string, string>(); `

**The same request header is working fine when I have changed to** 

`var headers = {};`

**Comment by sneas** [comment]
Hi @rajamuthur. The new version (6.2.0) #86 has been released today. Headers do not use Map anymore. This might solve the problem. Please let me know if it still exists.

**Comment by rajamuthur** [comment]
Hi @sneas ,
Getting following error after upgraded plugin version to 6.2.0 from 4.0.7.

![6 2 0_backend_http_error](https://user-images.githubusercontent.com/10390662/65021996-ca39b700-d94d-11e9-86a0-3ccd44c54039.png)

### **Please find Ionic info details:**

**_Ionic:_**
   ionic (Ionic CLI)  : 4.11.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11
   
**_Cordova:_**
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.0, (and 21
other plugins)

**_System:_**
   Android SDK Tools : 26.1.1 
   NodeJS            : v8.12.0
   npm               : 6.8.0
   OS                : Windows 8.1

**Note:**
In my current project i have used as
import { Platform } from 'ionic-angular';
import { HTTP } from '@ionic-native/http';

**Comment by sneas** [comment]
You have to update @ionic-native/http. Please follow the instructions
https://ionicframework.com/docs/native/http/#installation

**Comment by sneas** [comment]
I guess 6.2.0 is not compatible with Ionic 3 + Ionic native 4.

I will provide a fix for your version shortly.

**Comment by sneas** [comment]
v4.0.11 has been released. It uses Object instead of Map. Should fix your issue.
