### ISSUE TITLE
PATCH support

### ISSUE THREAD

**Issue by anphu7492** [sneas/ionic-native-http-connection-backend#9]
I notice that it's a known issue but is there any workaround for PATCH method?

**Comment by sneas** [comment]
It's limitation of https://github.com/sneas/cordova-HTTP2 which is a fork of original https://github.com/wymsee/cordova-HTTP with PUT and DELETE methods added by Sebastian Puentes (I can't find him on GitHub). I think we can add PATH method support in https://github.com/sneas/cordova-HTTP2 the same way PUT method implemented. I can have a close look at it on the weekend. Or you can create PR yourself if you like.

**Comment by sneas** [comment]
So, cordaova-HTTP2 (android part) depends on https://github.com/kevinsawicki/http-request which doesn't support PATCH: https://github.com/kevinsawicki/http-request/issues/119.
