### ISSUE TITLE
How to bypass ionic-native-http-connection-backend for some pages?

### ISSUE THREAD

**Issue by sbchopade** [sneas/ionic-native-http-connection-backend#90]
Hello sir,
If I want to use HttpClientModule (For both mobile as well as browser) instead of this module but only for some page (not for all page). How to achieve this? Thanks

**Comment by sneas** [comment]
Sir,

The intention of this library is to transparently route all the requests through Native HTTP whenever possible. So there is no way to disable Native HTTP in a certain scenario.

But there is a way to handle this by creating your own `HttpBackend` provider:

```typescript
providers: [
  // This is the librarie's HttpBackendProvider which decides whether to use Native HTTP or XHR
  {provide: NativeHttpFallback, useClass: NativeHttpFallback, deps: [Platform, NativeHttpBackend, HttpXhrBackend]},
  {provide: HttpBackend, useClass: YourOwnBackendProviderWhichCanDecideWhetherToUseNativeHttpBackendOrNot, deps: [NativeHttpFallback, HttpXhrBackend]},
],
```

```typescript
class YourOwnBackendProviderWhichCanDecideWhetherToUseNativeHttpBackendOrNot implements HttpBackend {
  constructor(private nativeHttp: HttpBackend, private xhr: HttpBackend) {}

  handle(req: HttpRequest<any>): Observable<HttpEvent<any>> {
    if (req.headers.has('XHR-please')) {
      return this.xhr.handle(req);
    } else {
      return this.nativeHttp.handle(req);
    }
  }
}
```

And whenever you'd like to use-XHR-no-matter-what, you do:

```typescript
import { HttpHeaders } from '@angular/common/http';

this.httpClient.get('http://host', {
  headers: new HttpHeaders({
            'XHR-please': 'yes, sir'
        })
});
```

I hope this makes sense :)

**Comment by sbchopade** [comment]
Hello sneas,
I am getting this error ... No static injector for NativeHttpFallback.

**Comment by sneas** [comment]
Here is the fully working example https://github.com/sneas/ionic-4-http-test/blob/force-xhr/src/app/app.module.ts

**Comment by sbchopade** [comment]
Hello sneas,
Your are great. You saved my day. Thank you so much for such a wonderful repo and solution too.
