### ISSUE TITLE
compile errors cannot find module

### ISSUE THREAD

**Issue by kirtipriya** [sneas/ionic-native-http-connection-backend#92]
Below is the error I get when i try to run ionic cordova prepare ios
_ionic cordova prepare ios
> ionic-app-scripts build --target cordova --platform ios
[23:40:15]  ionic-app-scripts 3.1.9 
[23:40:15]  build dev started ... 
[23:40:15]  clean started ... 
[23:40:15]  clean finished in 9 ms 
[23:40:15]  copy started ... 
[23:40:15]  deeplinks started ... 
[23:40:17]  deeplinks finished in 1.21 s 
[23:40:17]  transpile started ... 
[23:40:26]  typescript: node_modules/ionic-native-http-connection-backend/dist/native-http-backend.d.ts, line: 2 
            Cannot find module '@ionic-native/http/ngx'. 

       L1:  import { HttpBackend, HttpEvent, HttpRequest } from '@angular/common/http';
       L2:  import { HTTP } from '@ionic-native/http/ngx';
       L3:  import { Observable } from 'rxjs';

[23:40:26]  typescript: node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.d.ts, line: 2 
            Cannot find module '@ionic/angular'. 

       L1:  import { HttpBackend, HttpEvent, HttpRequest } from '@angular/common/http';
       L2:  import { Platform } from '@ionic/angular';
       L3:  import { Observable } from 'rxjs';

[23:40:26]  ionic-app-script task: "build" 
[23:40:26]  Error: Failed to transpile program_ 

@ionic-native/http/ngx gives error , because there is no folder with the name ngx inside http
@ionic-angular gives error because ionic-angular should be the value.
After I solve these (by removing ngx and adding ionic-angular), it gives me a bigger compile error

[23:22:22]  ionic-app-script task: "build" 
[23:22:22]  Error: ./node_modules/ionic-native-http-connection-backend/dist/native-http-module.js Module not found: 
            Error: Can't resolve '@ionic-native/http/ngx' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-bac
kend/dist'
            resolve '@ionic-native/http/ngx' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-bac
kend/dist'
            Parsed request is a module using description file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-back
end/package.json
            (relative path: ./dist) Field 'browser' doesn't contain a valid alias configuration after using descriptio
n 
            file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-back
end/package.json
            (relative path: ./dist) resolve as module looking for modules in 
            /Users/username/Documents/appname/node_modules using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            Field 'browser' doesn't contain a valid alias configuration after using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            using description file: 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/package.json 
            (relative path: ./ngx) no extension Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't 
            exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts doesn't 
            exist .js Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js doesn't 
            exist .json Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json doesn't 
            exist as directory 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't 
            exist [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx] @ 
            ./node_modules/ionic-native-http-connection-backend/dist/native-http-module.js 9:0-46 @ 
            ./node_modules/ionic-native-http-connection-backend/dist/index.js @ ./src/app/app.module.ts @ 
            ./src/app/main.ts,./node_modules/ionic-native-http-connection-backend/dist/native-http-backend.js Module not 
            found: Error: Can't resolve '@ionic-native/http/ngx' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
            resolve '@ionic-native/http/ngx' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
            Parsed request is a module using description file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json
            (relative path: ./dist) Field 'browser' doesn't contain a valid alias configuration after using description 
            file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json
            (relative path: ./dist) resolve as module looking for modules in 
            /Users/username/Documents/appname/node_modules using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            Field 'browser' doesn't contain a valid alias configuration after using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            using description file: 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/package.json 
            (relative path: ./ngx) no extension Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't 
            exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts doesn't 
            exist .js Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js doesn't 
            exist .json Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json doesn't 
            exist as directory 
            /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't 
            exist [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json] 
            [/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx] @ 
            ./node_modules/ionic-native-http-connection-backend/dist/native-http-backend.js 23:0-46 @ 
            ./node_modules/ionic-native-http-connection-backend/dist/index.js @ ./src/app/app.module.ts @ 
            ./src/app/main.ts,./node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.js Module 
            not found: Error: Can't resolve '@ionic/angular' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
            resolve '@ionic/angular' in 
            '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
            Parsed request is a module using description file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json
            (relative path: ./dist) Field 'browser' doesn't contain a valid alias configuration after using description 
            file: 
            /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json
            (relative path: ./dist) resolve as module looking for modules in 
            /Users/username/Documents/appname/node_modules using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            Field 'browser' doesn't contain a valid alias configuration after using description file: 
            /Users/username/Documents/appname/package.json (relative path: ./node_modules) 
            using description file: /Users/username/Documents/appname/package.json (relative 
            path: ./node_modules/@ionic/angular) no extension Field 'browser' doesn't contain a valid alias 
            configuration /Users/username/Documents/appname/node_modules/@ionic/angular 
            doesn't exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic/angular.ts doesn't exist .js 
            Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic/angular.js doesn't exist 
            .json Field 'browser' doesn't contain a valid alias configuration 
            /Users/username/Documents/appname/node_modules/@ionic/angular.json doesn't exist 
            as directory /Users/username/Documents/appname/node_modules/@ionic/angular doesn't 
            exist [/Users/username/Documents/appname/node_modules/@ionic/angular] 
            [/Users/username/Documents/appname/node_modules/@ionic/angular.ts] 
            [/Users/username/Documents/appname/node_modules/@ionic/angular.js] 
            [/Users/username/Documents/appname/node_modules/@ionic/angular.json] 
            [/Users/username/Documents/appname/node_modules/@ionic/angular] @ 
            ./node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.js 13:0-42 @ 
            ./node_modules/ionic-native-http-connection-backend/dist/index.js @ ./src/app/app.module.ts @ 
            ./src/app/main.ts 
Error: ./node_modules/ionic-native-http-connection-backend/dist/native-http-module.js
Module not found: Error: Can't resolve '@ionic-native/http/ngx' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
resolve '@ionic-native/http/ngx' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
  Parsed request is a module
  using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    resolve as module
      looking for modules in /Users/username/Documents/appname/node_modules
        using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          using description file: /Users/username/Documents/appname/node_modules/@ionic-native/http/package.json (relative path: ./ngx)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json doesn't exist
            as directory
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't exist
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx]
 @ ./node_modules/ionic-native-http-connection-backend/dist/native-http-module.js 9:0-46
 @ ./node_modules/ionic-native-http-connection-backend/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts,./node_modules/ionic-native-http-connection-backend/dist/native-http-backend.js
Module not found: Error: Can't resolve '@ionic-native/http/ngx' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
resolve '@ionic-native/http/ngx' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
  Parsed request is a module
  using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    resolve as module
      looking for modules in /Users/username/Documents/appname/node_modules
        using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          using description file: /Users/username/Documents/appname/node_modules/@ionic-native/http/package.json (relative path: ./ngx)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json doesn't exist
            as directory
              /Users/username/Documents/appname/node_modules/@ionic-native/http/ngx doesn't exist
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.ts]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.js]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx.json]
[/Users/username/Documents/appname/node_modules/@ionic-native/http/ngx]
 @ ./node_modules/ionic-native-http-connection-backend/dist/native-http-backend.js 23:0-46
 @ ./node_modules/ionic-native-http-connection-backend/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts,./node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.js
Module not found: Error: Can't resolve '@ionic/angular' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
resolve '@ionic/angular' in '/Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/dist'
  Parsed request is a module
  using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/username/Documents/appname/node_modules/ionic-native-http-connection-backend/package.json (relative path: ./dist)
    resolve as module
      looking for modules in /Users/username/Documents/appname/node_modules
        using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules)
          using description file: /Users/username/Documents/appname/package.json (relative path: ./node_modules/@ionic/angular)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic/angular doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic/angular.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic/angular.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/Documents/appname/node_modules/@ionic/angular.json doesn't exist
            as directory
              /Users/username/Documents/appname/node_modules/@ionic/angular doesn't exist
[/Users/username/Documents/appname/node_modules/@ionic/angular]
[/Users/username/Documents/appname/node_modules/@ionic/angular.ts]
[/Users/username/Documents/appname/node_modules/@ionic/angular.js]
[/Users/username/Documents/appname/node_modules/@ionic/angular.json]
[/Users/username/Documents/appname/node_modules/@ionic/angular]
 @ ./node_modules/ionic-native-http-connection-backend/dist/native-http-fallback.js 13:0-42
 @ ./node_modules/ionic-native-http-connection-backend/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (/Users/username/Documents/appname/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/username/Documents/appname/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/username/Documents/appname/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/username/Documents/appname/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/username/Documents/appname/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/username/Documents/appname/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/username/Documents/appname/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/username/Documents/appname/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/username/Documents/appname/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/username/Documents/appname/node_modules/webpack/lib/Compiler.js:365:9)

This is my ionic info:
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.2.1, (and 19 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Library/Android/sdk)
   NodeJS            : v8.11.1 (/usr/local/bin/node)
   npm               : 3.10.10
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

Can you help regarding this

**Comment by sneas** [comment]
What is the version of `@ionic-native/core` ?

**Comment by kirtipriya** [comment]
The version is:

"@ionic-native/core": "4.12.0"

**Comment by sneas** [comment]
ionic-native-http-coonection-backend@4.0.11 is the last version supporting
ionic@3 and ionic-native@4.

**Comment by kirtipriya** [comment]
Thanks @sneas , I will try this version

**Comment by kirtipriya** [comment]
Hi @sneas , there are no compile error and app builds successfully.
Is this pllugin going to solve the issue at https://bugs.webkit.org/show_bug.cgi?id=200857
This issue is about cookies not being set in the wkwebview in the new ios 13 
This was my main reason to install the plugin
The cookie setting did not work unfortunately

**Comment by sneas** [comment]
This library is an adapter between `HttpClientModule` and `NativeHTTP`. Its intention is to let `HttpClient` to transparently perform HTTP request through `NativeHTTP` in order to solve the browser's CORS limitation. It does not solve cross-domain cookie issues.

However, you can perform cookies manipulation by calling appropriate methods of `ionic-native/HTTP` https://ionicframework.com/docs/v3/native/http/

For example `setCookie(url, cookie)` sets cookies for an appropriate URL and later those cookies will be used while performing an HTTP request to this URL.
