### ISSUE TITLE
Doesn't parse Blobs correctly

### ISSUE THREAD

**Issue by madmandrew** [sneas/ionic-native-http-connection-backend#96]
It appears this plugin doesn't parse blob data correctly.

I've made GET request for both an image and video file and neither work with this plugin

**Comment by sneas** [comment]
Hi, thank you for rasing the  the issue. Could you please provide a reproducible example?
Feel free to fork https://github.com/sneas/ionic-4-http-test it already contains necessary presets for up and running.

**Comment by sneas** [comment]
Closing the issue due to the inability to reproduce the problem.
